fix: update azure-kv plugin version to v1.0.1
AzureCR/notation-ado-task pull request #5
Opened 2023-09-05 09:06 UTC by JeyJeyGao

Signed-off-by: Junjie Gao <junjiegao@microsoft.com>

2023-09-06 01:50 UTC, shizhMSFT requested changes
Also, we need to change the default version for installation

2023-09-06 01:50 UTC, shizhMSFT commented on NotationV0/data/azure_kv_versions.json
Instead of changing the version from v1.0.0 to v1.0.1, please add a new version

2023-09-06 02:05 UTC, JeyJeyGao commented on NotationV0/data/azure_kv_versions.json
It always installs latest version of notation akv plugin, so there is no longer a need for v1.0.0.

2023-09-06 02:06 UTC, JeyJeyGao commented on NotationV0/data/azure_kv_versions.json
User cannot choose AKV plugin version.

2023-09-07 05:23 UTC, JeyJeyGao commented on NotationV0/data/azure_kv_versions.json
Updated.

2023-09-08 08:08 UTC, shizhMSFT approved these changes
LGTM

2023-09-12 01:10 UTC, merged